[package]
name = "keyvault"
version = "0.1.0"
edition.workspace = true


[dependencies]
anyhow.workspace = true
tokio.workspace = true
azure_identity = "0.28.0"
azure_security_keyvault_secrets = "0.7.0"
