[package]
name = "api"
edition.workspace = true

[lints]
# workspace = true

[dependencies]
bytes.workspace = true
http.workspace = true
http-body = "1.0.1"
http-body-util = "0.1"
serde.workspace = true
serde_json.workspace = true
